import type { Metadata } from "next";
import { Inter, Roboto, Orbitron } from "next/font/google";
import "./globals.css";
import ClientSideWrapper from "@/components/ClientSideWrapper";
import Navbar from "@/components/Navbar";
import { orbitron, roboto } from "./fonts";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Thomas Augot | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${orbitron.variable} ${roboto.variable}`}>
      <body className={`${inter.className} bg-primary-bg`}>
        <ClientSideWrapper>
          <Navbar />
          {children}
        </ClientSideWrapper>
      </body>
    </html>
  );
}
