import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ClientSideWrapper from "@/components/ClientSideWrapper";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} p-4 bg-gradient-to-r from-zinc-700 to-zinc-900`}
      >
        <ClientSideWrapper>
          <Navbar />
        </ClientSideWrapper>
      </body>
    </html>
  );
}
